controllers:
    resource: ../src/Controller/
    type: attribute

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
edit_lucky_number:
    path: /lucky/edit/{id}-{slug}
    controller: App\Controller\LuckyController::edit