<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZJtcqbz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZJtcqbz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZJtcqbz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZJtcqbz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZJtcqbz\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZJtcqbz',
    'container.build_id' => '24b71672',
    'container.build_time' => 1658913164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZJtcqbz');
